version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=internet-magaz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abobus
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d internet-magaz" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=abobus
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=internet-magaz
    ports:
      - '8005:8000'
    volumes:
      - ./assets:/app/assets
